name: Bump build version

on:
  push:
    branches: [ main ]

env:
  VERSION_UPDATE_TYPE: "value"

jobs:
  bump:
    runs-on: ubuntu-latest
    name: Build and bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8

      - name: Restore dependencies
        run: dotnet restore SpendManagement.Receipts.Contracts/Contracts.csproj

      - name: Determinar Tipo de Mudança
        id: determine_change_type
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if echo "$LAST_COMMIT_MESSAGE" | grep -qiE "feat"; then
            echo "VERSION_UPDATE_TYPE=MINOR" >> $GITHUB_ENV
          fi
          if echo "$LAST_COMMIT_MESSAGE" | grep -qiE "fix"; then
            echo "VERSION_UPDATE_TYPE=REVISION" >> $GITHUB_ENV
          fi

      - name: Print Update type
        run: |
          echo "Tipo de Mudança: $VERSION_UPDATE_TYPE"

      - name: Build
        run: dotnet build SpendManagement.Receipts.Contracts/Contracts.csproj

      - name: Bump build version - Minor
        if: env.VERSION_UPDATE_TYPE == 'MINOR'
        id: bump-minor
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: SpendManagement.Receipts.Contracts/Contracts.csproj
          version: bump-minor

      - name: Bump build version - Revision
        if: env.VERSION_UPDATE_TYPE == 'REVISION'
        id: bump-revision
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: SpendManagement.Receipts.Contracts/Contracts.csproj
          version: bump-revision

      - name: Commit and push changes
        if: ${{ always() }}
        run: |
          git config user.name "Build - Incrementing version | Github action"
          git config user.email "deploy@spendmanagement.com"
          git add .
          git commit -m "Bump project version to ${{ steps.bump-minor.outputs.newVersion }} ${{ steps.bump-revision.outputs.newVersion }}"
          git push
          
  build:
    runs-on: ubuntu-latest
    needs: bump
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: 8.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore SpendManagement.Receipts.Contracts/Contracts.csproj
        
      - name: Build
        run: dotnet build --no-restore --configuration Release SpendManagement.Receipts.Contracts/Contracts.csproj
      - name: Build solution and generate NuGet package
        run: |  
          cd SpendManagement.Receipts.Contracts
          dotnet pack Contracts.csproj -c Release -o out 

      - name: Push generated package to GitHub registry 
        run: dotnet nuget push ./SpendManagement.Receipts.Contracts/out/*.nupkg --api-key ${{ secrets.WEBCONTRACTS_API_KEY }} --source https://api.nuget.org/v3/index.json
