name: build_and_run_tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION_UPDATE_TYPE: "value"

jobs:
  build-project:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: 8.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: dotnet build --configuration Release SpendManagement.Receipts.Contracts/Contracts.csproj
    
  update-project-version:
    runs-on: ubuntu-latest
    name: Change csproj version
    needs: [build-project]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Restore dependencies
        run: dotnet restore SpendManagement.Receipts.Contracts/Contracts.csproj

      - name: Determinar Tipo de Mudança
        id: determine_change_type
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if echo "$LAST_COMMIT_MESSAGE" | grep -qiE "feat"; then
            echo "VERSION_UPDATE_TYPE=MINOR" >> $GITHUB_ENV
          fi
          if echo "$LAST_COMMIT_MESSAGE" | grep -qiE "fix"; then
            echo "VERSION_UPDATE_TYPE=REVISION" >> $GITHUB_ENV
          fi

      - name: Print Update type
        run: |
          echo "Tipo de Mudança: $VERSION_UPDATE_TYPE"

      - name: Build
        run: dotnet build SpendManagement.Receipts.Contracts/Contracts.csproj

      - name: Bump build version - Minor
        if: env.VERSION_UPDATE_TYPE == 'MINOR'
        id: bump-minor
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: SpendManagement.Receipts.Contracts/Contracts.csproj
          version: "*.^.0"

      - name: Bump build version - Revision
        if: env.VERSION_UPDATE_TYPE == 'REVISION'
        id: bump-revision
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: SpendManagement.Receipts.Contracts/Contracts.csproj
          version: "*.*.^"

      - name: Commit and push changes
        if: env.VERSION_UPDATE_TYPE == 'REVISION' || env.VERSION_UPDATE_TYPE == 'MINOR'
        run: |
          git config user.name "CI - Incrementing version"
          git config user.email "deploy@spendmanagement.com"
          git add .
          git commit -m "CI: Updating application version"
          git push         

  publish-nuGet-package:
    runs-on: ubuntu-latest
    needs: [update-project-version]
    if: github.ref == 'refs/heads/main'
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: 8.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean output directory
        run: |
          if [ -d "SpendManagement.Receipts.Contracts/out" ]; then
            rm -r SpendManagement.Receipts.Contracts/out
          fi

      - name: Restore dependencies
        run: dotnet restore SpendManagement.Receipts.Contracts/Contracts.csproj
        
      - name: Build solution and generate NuGet package
        run: | 
          dotnet build --no-restore --configuration Release SpendManagement.Receipts.Contracts/Contracts.csproj
          cd SpendManagement.Receipts.Contracts
          dotnet pack Contracts.csproj -c Release -o out 

      - name: Push generated package to GitHub registry 
        run: dotnet nuget push ./SpendManagement.Receipts.Contracts/out/*.nupkg --api-key ${{ secrets.WEBCONTRACTS_API_KEY }} --source https://api.nuget.org/v3/index.json
