name: Bump build version

on:
  push:
    branches: [ main ]

jobs:
  bump:
    runs-on: ubuntu-latest
    name: Build and bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8

      - name: Restore dependencies
        run: dotnet restore SpendManagement.WebContracts/Web.Contracts.csproj

      - name: Build
        run: dotnet build SpendManagement.WebContracts/Web.Contracts.csproj

      - name: Bump build version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: SpendManagement.WebContracts/Web.Contracts.csproj
          version: bump-build

      - run: |
          git config user.name "Build - Github Actions"
          git config user.email "your-email@users.noreply.github.com"
          git add .
          git commit -m "Bump project version to ${{ steps.bump.outputs.newVersion }}"
          git push
          
  build:
    runs-on: ubuntu-18.04
    needs: bump
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
          
      - name: Build solution and generate NuGet package
        run: |  
          cd SpendManagement.WebContracts/Web.Contracts.csproj
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push SpendManagement.WebContracts.${{ steps.bump.outputs.newVersion }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
